#pragma once

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define CAPS_WORD_INVERT_ON_SHIFT

#define RGB_MATRIX_SLEEP
#define RGB_MATRIX_DEFAULT_ON false
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR
